Create news page
devojka-od-papira/workco-project pull request #10
Opened 2022-10-10 23:24 UTC by devojka-od-papira

2022-10-11 11:30 UTC, sutija requested changes

2022-10-11 11:30 UTC, sutija commented on src/components/container/index.tsx
> +}
Nema potrebe za ovim, s obzirom da se vec nalazi unutar React.FC. :)

2022-10-11 11:30 UTC, sutija commented on src/components/mainNews/index.tsx
> +      <div className={styles.img} />
Fali nam image :)

2022-10-11 11:30 UTC, sutija commented on src/components/mainNews/index.tsx
> +      <p className={styles.news}>
Bilo bi dobro da ovo nazivamo pravim imenom: `styles.shortText` ili `styles.text`...

2022-10-11 11:30 UTC, sutija commented on src/components/news/index.tsx
> +  hideTitle?: boolean | undefined;
`?` = undefined
`hideTitle?: boolean;`

2022-10-11 11:30 UTC, sutija commented on src/components/news/index.tsx
> +const News: React.FC<NewsProps> = ({ hideTitle = false, button }) => {
S obzirom da moze bude undefined | true | false, ne moramo da definisemo default vrednost `hideTitle`.

2022-10-11 11:30 UTC, sutija commented on src/components/news/index.tsx
> +    <Section hideTitle={hideTitle} classNames={styles.section} title="News">
Nema potrebe za `hideTitle` s obzirom da sami odlucujemo da li cemo proslediti title ili ne. U ovom slucaju samo treba da uklonimo `title` prop.

2022-10-11 11:30 UTC, sutija commented on src/components/news/index.tsx
> +      <Grid>{button}</Grid>
```
<Button onClick={() => {loadMoreNews()}}>Load more news</Button>
```

2022-10-11 11:30 UTC, sutija commented on src/components/section/index.tsx
> +  hideTitle?: boolean;
kako bi smo izbegli hideTitle, mozemo napraviti da je `title` opcion.

2022-10-11 11:30 UTC, sutija commented on src/views/home/index.tsx
> +      }
:'(

2022-10-11 11:30 UTC, sutija commented on src/views/newsView/index.tsx
> +    />
:'(

2022-10-11 11:30 UTC, sutija commented on src/App.tsx
> +  </BrowserRouter>
```
<Header />
<BrowserRouter>
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="/news" element={<NewsView />} />
    </Routes>
  </BrowserRouter>
  <Footer />
```

2022-10-13 15:18 UTC, sutija commented on src/components/section/index.tsx
> +      </h3>
Da li nam treba `h3` element ako nemamo title?

2022-10-13 15:18 UTC, sutija commented on src/components/news/index.tsx
> +const News: React.FC<NewsProps> = ({ title, buttonText, classNames }) => {
Dogovorili smo se da necemo istu komponentu da koristimo za home i za news. Vec samo listu news-a.

2022-10-13 15:18 UTC, sutija commented on src/views/newsView/index.tsx
> +    <News buttonText="Load more news" classNames={styles.moreNewsWrapper} />
Ovde ne treba da ide cela news komponenta koja se koristi na naslovnoj strani.

2022-10-13 15:18 UTC, sutija commented on src/components/news/index.tsx
>        <Grid>
Samo od ovog dela treba napraviti reusable komponentu.

2022-10-13 20:11 UTC, devojka-od-papira commented on src/components/news/index.tsx
>        <Grid>
ne razumem kako to da odradim, moze pomoc

2022-10-14 10:06 UTC, sutija commented on src/components/section/index.tsx
>  const Section: React.FC<SectionProps> = ({ title, children, classNames }) => (
Preimenovati ovu komponentu u `HomeSection` kako bi izbegli zabunu. :)

2022-10-14 10:06 UTC, sutija commented on src/routes/index.tsx
> +];
```
export const ROUTES = {
     HOME: '/',
     CLASSES: '/classes',
     ...
}
```

2022-10-14 10:06 UTC, sutija commented on src/App.tsx
> +      ))}
`<Route path={ROUTES.HOME} element={<Home />} />`

2022-10-14 10:06 UTC, sutija commented on src/views/newsView/index.tsx
> +      </Container>
Ovo treba da bude `NewsList` reusable komponenta. ;)

2022-10-18 08:36 UTC, sutija commented on src/views/newsView/index.tsx
> +      <NewsList newsData={newsData} />
S obzirom da je `newsData[0]` (prva vest) vec prikazana u glavnoj vesti, mislim da ne treba da se nadje i u `NewsList`, sto znaci da je treba ukloniti iz tog niza. :)

Preporucujem da koristis `splice` metodu.

2022-10-18 08:36 UTC, sutija commented on src/views/newsView/index.tsx
> +      <Button text="Load more news" />
<img width="512" alt="Screenshot 2022-10-18 at 10 31 30" src="https://user-images.githubusercontent.com/3923155/196379211-164df010-f9d8-47ef-a780-814cd4a80a84.png">

2022-10-18 08:36 UTC, sutija commented on src/views/newsView/index.tsx
> +      <Button text="Load more news" />
<img width="295" alt="Screenshot 2022-10-18 at 10 32 49" src="https://user-images.githubusercontent.com/3923155/196379328-e9298cc7-74db-4aef-8bf9-04fe814db4ff.png">

2022-10-18 08:37 UTC, sutija commented
<img width="367" alt="Screenshot 2022-10-18 at 10 35 45" src="https://user-images.githubusercontent.com/3923155/196380287-eec38b53-9c84-4196-8027-3f31a2bf9f75.png">

Na mobilnom prikazu nema razmaka izmedju vesti.

2022-10-18 08:37 UTC, sutija approved these changes

2022-10-18 09:30 UTC, merged