Classes
devojka-od-papira/workco-project pull request #4
Opened 2022-08-31 11:26 UTC by devojka-od-papira

2022-09-08 15:40 UTC, sutija commented
- title ne zauzima dve kolone
- pozadina naslova treba da ima transparentnost

![Screenshot 2022-09-08 at 17 39 09](https://user-images.githubusercontent.com/3923155/189165386-6e7d3db1-f137-42bc-b225-f797bfa1d32a.png)

2022-09-08 15:45 UTC, sutija requested changes

2022-09-08 15:45 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +
:'(

2022-09-08 15:45 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  background-color: #343434;
Rekli smo da cemo da koristimo varijable za boje. :)

2022-09-08 15:45 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  align-items: center;
Ne moramo ovo sa display flex, dovoljno bi nam bio samo padding.

2022-09-08 15:45 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  top: 247px;
Bolje je da stavimo bottom nego top u slucaju da nam tekst zauzima 2 reda, da ne probija van elementa.

2022-09-09 11:26 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  margin-left: 23px;
zar ne treba da imamo padding ovde? :)

2022-09-09 11:26 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  background-color: rgba(52, 52, 52, .43);
Hajde da stavimo i ovu boju u varijablu.

2022-09-09 11:26 UTC, sutija commented on src/components/section/index.tsx
> +        </h3>
Rekli smo da hocemo kroz props da definisemo boju.

2022-09-12 15:54 UTC, sutija commented on src/components/section/index.tsx
> +        <h3 className={cx(styles.title, { classNames })}>{title}</h3>
zasto koristimo 2x `classNames`?

2022-09-12 15:56 UTC, devojka-od-papira commented on src/components/section/index.tsx
> +        <h3 className={cx(styles.title, { classNames })}>{title}</h3>
jedno je className a drugo je classNames

2022-09-13 11:05 UTC, sutija approved these changes

2022-09-13 11:07 UTC, merged