App is mobile responsive
devojka-od-papira/workco-project pull request #7
Opened 2022-09-16 10:00 UTC by devojka-od-papira

2022-09-16 10:10 UTC, sutija requested changes

2022-09-16 10:10 UTC, sutija commented on src/components/classItem/ClassItem.module.scss
> +  }
```
margin-bottom: 0;

@include breakpoint(desktop) {
margin-bottom: 47px;
}

```

2022-09-16 10:10 UTC, sutija commented on src/components/classes/Classes.module.scss
> +  }
🥇

2022-09-16 10:10 UTC, sutija commented on src/components/header/Header.module.scss
> +    padding-left: 2% !important;
Hajde da probamo stilove bez `important`;

2022-09-16 10:10 UTC, sutija commented on src/components/logo/Logo.module.scss
> +    width: 104%;
Mislim da logo ne treba da nam bude 104%.

2022-09-22 14:04 UTC, sutija commented on src/components/icon/Icon.module.scss
> +  right: 9%;
Hajde da napravimo u `variables.scss` varijable za margine i da ih onda koristimo na vise mesta.

2022-09-22 14:06 UTC, sutija commented on src/components/logo/Logo.module.scss
> +    width: 100%;
Ovo je nepotrebno jer se radi o div elementu. Div element sam po sebi je `display: block;` sto znaci da ce se automatski rasiriti na 100%.

2022-09-22 14:12 UTC, sutija commented on src/components/news/News.module.scss
> +
grrr...

2022-09-22 14:13 UTC, sutija commented on src/components/news/News.module.scss
> +  @include breakpoint(mobileOnly) {
Zbog logike stvari, iako u ovom slucaju ne menja nista uvek idemo na ovaj redosled: mobile, tablet, desktop;

2022-09-22 14:14 UTC, sutija commented on src/components/newsItem/NewsItem.module.scss
> +  }
Ako smo odradili include pod .description, nema potrebe da to ponavljamo za svaki breakpoint.

2022-09-22 14:14 UTC, sutija commented on src/components/newsItem/NewsItem.module.scss
> +  }
U ovom slucaju, bolje da je po defaultu `h4`, a da samo pod `desktop` stavimo da je `h2`.

2022-09-22 14:15 UTC, sutija commented on src/components/section/Section.module.scss
> +  }
Ista situacija sa `h2` i `h1`, kao i za font-size i line-height.

2022-09-22 14:17 UTC, sutija commented on src/components/section/Section.module.scss
> +      right: -14% !important;
<img width="179" alt="Screenshot 2022-09-22 at 16 16 54" src="https://user-images.githubusercontent.com/3923155/191771924-7ef13941-f1db-485d-86c1-a825682424b8.png">
<img width="210" alt="Screenshot 2022-09-22 at 16 16 30" src="https://user-images.githubusercontent.com/3923155/191771927-42905cbf-d650-4930-9cb7-8e00ac68736c.png">


Deluje mi da ovo nije dobro, donja linija uvek treba da bude ista.

2022-09-27 11:12 UTC, sutija commented on src/components/logo/Logo.module.scss
> +.logo {
Please check if .logo and .logoSmall have same properties.

2022-09-27 11:12 UTC, sutija commented on src/components/news/News.module.scss
> +  margin-top: 29px;
Please check if we can avoid flex. For ex.

```
.moreNews {
...
margin: 0 auto;
}
```

2022-09-28 09:34 UTC, devojka-od-papira commented on src/components/news/News.module.scss
> +  margin-top: 29px;
Yes I did check, we can't avoid using flex.

2022-09-30 09:39 UTC, sutija approved these changes

2022-09-30 09:41 UTC, merged